name: Keep Backend Alive

on:
  schedule:
    - cron: '*/14 * * * *' # Run every 14 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  ping_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: |
          curl https://go-backend-zqxl.onrender.com/health
        env:
          CI: true
